"""Learning from typed corrections.

After FreeFlow inserts text, the text box it went into is watched for a while: its content is read
through UI Automation (Text or Value pattern, on the inspection thread with time-outs, so a slow
application can never block anything).  When the words that were inserted have been changed by hand
and the user has stopped typing, the changed words are reported: "loco host" -> "localhost" becomes a
learned rule (see learning.py).  Text the user appends is ignored, and so is a message that was sent
(the box became empty).  Games and controls that expose no text are simply not watched.
"""
from __future__ import annotations

import logging
import threading
import time
from typing import Callable, Optional

from . import focus
from .learning import extract_corrections

log = logging.getLogger(__name__)

UIA_TextPatternId = 10014
UIA_ValuePatternId = 10002
WATCH_SECONDS = 150.0     # how long after an insertion edits are watched for
POLL_S = 2.0              # how often the text box is read
SETTLE_S = 3.0            # an edit counts once the text has been unchanged this long and no key was pressed
MAX_TEXT = 40000          # characters read from the control at most
ANCHOR = 80               # characters before the insertion used to find it again


def _squash(s: Optional[str]) -> str:
    return " ".join((s or "").split())


def read_element_text(el) -> Optional[str]:
    """Text of a UI Automation element through its Text or Value pattern (inspection thread only)."""
    if el is None:
        return None
    from comtypes.gen import UIAutomationClient as UIA  # noqa: N814  (generated by focus._automation)
    try:
        p = el.GetCurrentPattern(UIA_TextPatternId)
        if p:
            return p.QueryInterface(UIA.IUIAutomationTextPattern).DocumentRange.GetText(MAX_TEXT)
    except Exception as e:
        log.debug("text pattern failed: %s", e)
    try:
        p = el.GetCurrentPattern(UIA_ValuePatternId)
        if p:
            return p.QueryInterface(UIA.IUIAutomationValuePattern).CurrentValue
    except Exception as e:
        log.debug("value pattern failed: %s", e)
    return None


def focused_element():
    uia = focus._automation()
    return uia.GetFocusedElement() if uia is not None else None


class EditWatcher:
    """Watches the control that received the last insertion; on_edit(wrong, right) for each changed span."""

    def __init__(self, on_edit: Callable[[str, str], None], key_presses: Callable[[], int]):
        self.on_edit = on_edit
        self.key_presses = key_presses
        self._gen = 0
        self._lock = threading.Lock()
        self.watching = False
        self.last_result = ""       # for tests / diagnostics

    def start(self, inserted: str, element_getter: Optional[Callable] = None):
        """Begin watching for edits of `inserted` in the control that has the focus right now."""
        with self._lock:
            self._gen += 1
            gen = self._gen
        threading.Thread(target=self._run, args=(gen, inserted, element_getter or focused_element),
                         name="edit-watch", daemon=True).start()

    def stop(self):
        with self._lock:
            self._gen += 1

    def _alive(self, gen: int) -> bool:
        return gen == self._gen

    def _read(self, getter, box: dict) -> Optional[str]:
        def fn():
            if box.get("el") is None:
                box["el"] = getter()
            return read_element_text(box.get("el"))
        try:
            value, status = focus._inspector.call(fn, 1.0)
        except Exception as e:
            log.debug("edit watch read failed: %s", e)
            return None
        return value if status == "ok" else None

    def _run(self, gen: int, inserted: str, getter):
        time.sleep(0.4)                       # let the application take the paste in
        target = _squash(inserted)
        if not target or not self._alive(gen):
            return
        box: dict = {}
        base = self._read(getter, box)
        if base is None:
            self.last_result = "no text access"
            log.debug("edit watch: the control exposes no text; not watching")
            return
        base_n = _squash(base)
        pos = base_n.rfind(target)
        if pos < 0:
            self.last_result = "inserted text not found"
            log.debug("edit watch: inserted text not found in the control; not watching")
            return
        before = base_n[max(0, pos - ANCHOR):pos]
        self.watching = True
        self.last_result = "watching"
        learned: set = set()
        last_region = target
        changed_at = 0.0
        presses = self.key_presses()
        end = time.time() + WATCH_SECONDS
        try:
            while time.time() < end and self._alive(gen):
                time.sleep(POLL_S)
                if not self._alive(gen):
                    break
                cur = self._read(getter, box)
                if cur is None:
                    continue
                cur_n = _squash(cur)
                if not cur_n:
                    region = ""           # the box was emptied: the message was sent or the text deleted
                elif before:
                    a = cur_n.rfind(before)
                    if a < 0:
                        continue          # text before the insertion changed too: cannot locate it now
                    region = cur_n[a + len(before):]
                else:
                    region = cur_n
                now = time.time()
                p = self.key_presses()
                if region != last_region or p != presses:
                    last_region, presses = region, p
                    changed_at = now
                    continue
                if region == target or not changed_at or now - changed_at < SETTLE_S:
                    continue
                if not region:
                    self.last_result = "text gone"
                    break                     # sent or deleted: nothing more to learn here
                pairs = [(s, d) for s, d in extract_corrections(target, region, strict=True) if (s.lower(), d.lower()) not in learned]
                for src, dst in pairs:
                    learned.add((src.lower(), dst.lower()))
                    try:
                        self.on_edit(src, dst)
                    except Exception:
                        log.exception("on_edit failed")
                changed_at = 0.0               # this state has been handled; wait for the next change
        finally:
            self.watching = False
            if self.last_result == "watching":
                self.last_result = "done"
